### ISSUE TITLE
checkSignificance when second == 0?

### ISSUE THREAD

**Issue by lcoombe** [bcgsc/arcs#86]
Look into what happens when `checkSignificance(int max, int second)` is called with `second = 0`. The call to `NormalEstimation` fails when translated to python, but doesn't seem to in C++. 
We need to look into the behaviour when `second = 0` and the impact (if any) on the results of ARCS.

**Comment by jowong4** [comment]
@lcoombe 
Added the following lines of code to `Arcs.cpp` to test.

```
		second = 0;

		/* Only insert edge if orientation with max links is dominant */
		if (checkSignificance(max, second)) {
			if (second == 0) {
				std::cout << "Passing if  = 0" << std::endl;
			}
```
Log output
```
=> Creating the graph... Mon Jan  6 07:56:18 2020
Passing if  = 0
Passing if  = 0
```
Seems like division by 0 means true lol

**Comment by lcoombe** [comment]
Interesting -- so basically fixing this bug shouldn't impact the results? Ie. if there is only link support for one orientation it passes this test anyway?

I do think we should fix it, but just so we're sure what the impact will be to the results.

**Comment by jowong4** [comment]
Not necessarily no impact. The current way is still incorrect for any `second` value less than max which means pretty much everything has unintended consequences currently. If possible, you can clone my new branch and run arcs on datasets that you normally use to check if performance is more or less the same. 

I suppose the biggest problem is, if it impacts performance, do we fix it or not? I'd still fix it because it's a bug but it never feels good to fix a bug only to get worse results.

**Comment by lcoombe** [comment]
Could you elaborate on what impact you think it will have, and what unintended consequences you are referring to? I'm talking about the actual scaffolding results. 
I'd appreciate if you could do the checks on your end -- Either way I don't want us to merge any changes until we run tests to understand the impact of the change.

**Comment by jowong4** [comment]
Well in the 0 case, it is dividing by 0. But that itself is unintended consequence. The main problem is second is not sum that is to say the number of trials is always less than the number of interested occurrences. As for how it will impact everything else, I can't speculate.

**Comment by lcoombe** [comment]
Well yes, but I was referring to the actual scaffolding results. I guess we will see the impact following some tests.
